### ISSUE TITLE
Issues in 1.12.2 port

### ISSUE THREAD

**Issue by Shazuli** [PC-Logix/OpenPrinter#44]
Ok, you probably know all of this, but here is a list of problems I found in OP as of this version (1.12.2-0.1.0.1):

- Most of the localization names are broken, with names such as `item.printer_ink_color.name`.
- The GUI's labels in the Printer, Shredder, and File Cabinet is broken as well.
- Item labels are not visible when the mouse hovers over the item while inside any of the mod's containers.
- The Folder has missing texture error on right click, and shift+right click causes the client to crash.
- The "center" parameter in `writeln()` function works unreliable. Works at times, but most times not.
- The machines are always facing "north".
- File Cabinet does not have a recipe.

I wouldn't write one of these normally because it's a direct port of an older version, but due to the confusion on CurseForge about this being a "released" build, can cause some disappointment for other people who has been anticipated this for a long time.
This is a fantastic addon and in my opinion should be part of the vanilla OpenComputers mod. But before downloading this version, beware of bugs! Not server friendly and should only be used in a singleplayer world with backups!

**Comment by CaitlynMainer** [comment]
Can you get me the crash log for shift+rclick?  I don’t have a pc atm but at least I can try to figure it out.

**Comment by Shazuli** [comment]
I don't have access to a computer myself too for about a week. But I'll send you the crash report as soon as I'm home.

**Comment by Shazuli** [comment]
I'll be home in

**Comment by Shazuli** [comment]
Whoops.
I wanted to say I'll send you the bugreport within the next 24 hours

**Comment by Shazuli** [comment]
Here is the crash report (this happens every time I shift+right click with the folder item):
[crash-2018-04-11_19.41.53-server.txt](https://github.com/PC-Logix/OpenPrinter/files/1899875/crash-2018-04-11_19.41.53-server.txt)

**Comment by CaitlynMainer** [comment]
@marcin212 Any thoughts here?   I'm hoping to have a computer again soon. (I've moved cross country and have nothing ATM) hard to program/debug on a phone.)

**Comment by marcin212** [comment]
@CaitlynMainer The language files are broken because the file name contains a capital letter (I think). The models are old (black cube with the texture on the front) because that's how they were in the 1.12.1 branch.

I'll try to fix the error as well as the language files as soon as I can. I'll need more free time for the models, though.

**Comment by marcin212** [comment]
Fixed:
- [x] Most of the localization names are broken, with names such as item.printer_ink_color.name. #45 
- [x] The GUI's labels in the Printer, Shredder, and File Cabinet is broken as well. #45
- [ ] Item labels are not visible when the mouse hovers over the item while inside any of the mod's containers.
- [x] The Folder has missing texture error on right click, and shift+right click causes the client to crash. #45
- [ ] The "center" parameter in writeln() function works unreliable. Works at times, but most times not.
- [ ] The machines are always facing "north".
- [ ] File Cabinet does not have a recipe.

**Comment by CaitlynMainer** [comment]
Thanks marcin

**Comment by CaitlynMainer** [comment]
I just pushed fixes for the rest of these issues.. a new build will be coming soon.
